package com.codes.wfhub.domain.entities.extension;

public enum CategoriesType {
    TECHNOLOGY_AND_IT,
    ENGINEERING,
    SALES_AND_BIZDEV,
    BUSINESS_AND_OPERATIONS,
    CREATIVE_AND_DESIGN,
    EDUCATION_AND_INSTRUCTION,
    CUSTOMER_SUPPORT,
    MARKETING_AND_COMMUNICATION,
    FINANCE_AND_ACCOUNTING,
    OTHER
}